[package]
name = "user/roblox-mamedrbx---showsystems"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Janitor = "howmanysmall/janitor@^1.17.0"